---
# tasks file for buldserver
- name: install many packages
  apt: name={{item}} state=present
  with_items:
    - openjdk-8-jdk
    - maven
    - git
- name: git clone boxfuse
  git:
    repo: '{{ git-repo }}'
    dest: '{{ work_dir }}'
    clone: yes
    update: yes
- name: mvn build
  command: mvn package
  args:
    chdir: '{{ work_dir }}'

- name: Copy artefact to master node
  fetch:
    src: '{{ src_folder_build }}/hello-1.0.war'
    dest: '{{ dest_folder_master }}/hello-1.0.war'
    flat: yes